services:
  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
      args:
        - API_BASE_URL=/api
        - FRONTEND_DIR=frontend
    environment:
      - API_BASE_URL=/api
      - VITE_API_BASE_URL=/api
      - NEXT_PUBLIC_API_BASE_URL=/api
    depends_on: [api]
    ports: ["8080:80"]
    # If you need to serve under /, leave as-is. If you want /app, adjust nginx config.
